class TestException(Exception):
  def __init__(self):
    print("Hello, this is an exception test")